/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Dictionary {
  static open(path: string): Dictionary
  static fromArray(keys: Array<string>): Dictionary
  /** Compiles a byte-sorted text file into an immutable binary FST. */
  static build(inputPath: string, outputPath: string): void
  /** Sorts a newline-delimited text file in-place by byte order. */
  static sort(path: string): void
  contains(key: string): boolean
  isEmpty(): boolean
  /** Returns the single top match for a query if it exists. */
  suggest(query: string): SearchResult | null
  /** Executes a fuzzy search query. */
  search(query: string, options?: SearchOptions | undefined | null): Array<SearchResult>
  len(): number
}

export interface SearchOptions {
  limit?: number
  distance?: number
  transposition?: boolean
  prefix?: boolean
}

export interface SearchResult {
  key: string
  distance: number
}
